variables:
  OMP_NUM_THREADS: "1"

image: debian:bookworm


cache:
# we use a constant string here, to reuse the cache as much as possible
    key: view-key
    paths:
        - .apt/

before_script:
  - mkdir -p .apt
  - export APT_CACHE_ARCHIVES="$(realpath .apt)"
  - apt-get update -yqq
  - apt-get install -y  -o dir::cache::archives="$APT_CACHE_ARCHIVES" make git gcc libgtk-3-dev libbart-dev

stages:
  - build
  - test

Build:
  stage: build
  script:
    - CFLAGS="-Werror" make all
  artifacts:
    paths:
      - view
      - cfl2png

Build_Analyzer:
  stage: build
  script:
    - CFLAGS="-fanalyzer -Werror" DEBUG=0 make all
  artifacts:
    paths:
      - view
      - cfl2png
    expire_in: 45 minutes
  allow_failure: true


Test_cfl2png:
  stage: test
  script:
    # no apt-get update here, as we just updated in the before_script
    - apt-get install -y  -o dir::cache::archives="$APT_CACHE_ARCHIVES" bart
    - bart phantom pha.ra
    - ./view -h
    - ./cfl2png -x1 -u0.5 -CV pha.ra pha.png
  artifacts:
    paths:
      - pha.png
  needs: [Build]
  dependencies:
     - Build
